## 服务端口
#server:
#  port: 8160
#
#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 10000
#        read-timeout: 10000
#  hystrix:
#    enabled: true
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/guli_edu?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    username: root
#    password: root
#  application:
#    name: service-ucenter
#  profiles:
#    active: dev
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  redis:
#    lettuce:
#      pool:
#        max-wait: 10000ms
#
#mybatis-plus:
##  configuration:
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/atguigu/ucenterservice/mapper/xml/*.xml
#
#logging:
#  level:
#    com.atguigu: debug
#    org.springframework: warn
#
##微信开放平台账号配置
#wx:
#  open:
#    app_id: wxed9954c01bb89b47
#    app_secret: a7482517235173ddb4083788de60b90e
#    redirect_url: http://localhost:8160/ucenterservice/wx/callback
##    redirect_url: http://frp.200073.xyz:4040/ucenterservice/wx/callback
