#server:
#  port: 8002
#spring:
#  application:
#    name: service-oss
#  profiles:
#    active: dev
#  servlet:
#    multipart:
#      max-file-size: 5MB
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
##阿里云 OSS
#aliyun:
#  oss:
#    file:
#      endpoint: oss-cn-shenzhen.aliyuncs.com
#      keyid: LTAI5tPkEaHFP2UWkyZbJ7Wy
#      keysecret: rkK8p6IIcSKhhdVI1wevyZvB21SoUi
#      bucketname: guli-edu-quan
#
